### ISSUE TITLE
GitHub: don't trigger the bot if # is in a link

### ISSUE THREAD

**Issue by B0pol** [TheAssassin/relbot#8]
If there is one link with #number in it, it will trigger the bot, it shouldn't

For example, when you write

> https://test.org/index.html#1

The bot says:

> [GitHub] Could not find anything for TeamNewPipe/html#1

**Comment by TheAssassin** [comment]
Detecting URLs is not really a good idea IMO, since hashes might occur in other places as well.

I once required a space before `#`. After fixing #6, reintroducing this won't really work easily any more. Nevertheless, I consider reintroducing something similar to that (although it'll probably mean doing it outside the main regular expression): require a space, unless you're at the message begin.

I don't remember the reason I removed that mandatory space again, though...
